spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: root

  sql:
    init:
      mode: always

  jpa:
    generate-ddl: false

    hibernate:
      ddl-auto: none

    show-sql: false
