DROP TABLE IF EXISTS USER_ROLE;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;

CREATE TABLE USER(
    id BIGINT NOT NULL AUTO_INCREMENT,
    login VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(500) NOT NULL,
    CONSTRAINT USER_ID_PK PRIMARY KEY (ID));

CREATE TABLE ROLE(
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL UNIQUE,
    CONSTRAINT ROLE_ID_PK PRIMARY KEY (ID));

CREATE TABLE USER_ROLE(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    CONSTRAINT USER_ROLE_PK PRIMARY KEY (user_id, role_id),
    CONSTRAINT USER_ROLE_U_FK FOREIGN KEY (user_id) REFERENCES USER(ID),
    CONSTRAINT USER_ROLE_R_FK FOREIGN KEY (role_id) REFERENCES ROLE(ID));

CREATE TABLE AUTHOR(
    id BIGINT NOT NULL AUTO_INCREMENT,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    CONSTRAINT AUTHOR_ID_PK PRIMARY KEY (ID));

CREATE TABLE GENRE(
    id BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(300) NOT NULL,
    CONSTRAINT GENRE_ID_PK PRIMARY KEY (ID));

CREATE TABLE BOOK(
    id BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(300) NOT NULL,
    publishingYear INTEGER,
    AUTHOR_ID BIGINT NOT NULL,
    GENRE_ID BIGINT NOT NULL,
    CONSTRAINT BOOK_ID_PK PRIMARY KEY (ID),
    CONSTRAINT BOOK_AUTHOR_FK FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID) ON DELETE CASCADE,
    CONSTRAINT BOOK_GENRE_FK FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID) ON DELETE CASCADE);