spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: root
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  main:
    allow-circular-references: true
