DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;

CREATE TABLE AUTHOR(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    CONSTRAINT AUTHOR_ID_PK PRIMARY KEY (ID));

CREATE TABLE GENRE(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(300) NOT NULL,
    CONSTRAINT GENRE_ID_PK PRIMARY KEY (ID));

CREATE TABLE BOOK(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(300) NOT NULL,
    publishingYear INTEGER,
    author_id BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    CONSTRAINT BOOK_ID_PK PRIMARY KEY (ID),
    CONSTRAINT BOOK_AUTHOR_FK FOREIGN KEY (author_id) REFERENCES AUTHOR(ID),
    CONSTRAINT BOOK_GENRE_FK FOREIGN KEY (genre_id) REFERENCES GENRE(ID));