DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;
DROP TABLE IF EXISTS GENRE;

CREATE TABLE USER(
    id BIGINT NOT NULL AUTO_INCREMENT,
    login VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(500) NOT NULL,
    CONSTRAINT AUTHOR_ID_PK PRIMARY KEY (ID));

CREATE TABLE AUTHOR(
    id BIGINT NOT NULL AUTO_INCREMENT,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    CONSTRAINT AUTHOR_ID_PK PRIMARY KEY (ID));

CREATE TABLE GENRE(
    id BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(300) NOT NULL,
    CONSTRAINT GENRE_ID_PK PRIMARY KEY (ID));

CREATE TABLE BOOK(
    id BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(300) NOT NULL,
    publishingYear INTEGER,
    AUTHOR_ID BIGINT NOT NULL,
    GENRE_ID BIGINT NOT NULL,
    CONSTRAINT BOOK_ID_PK PRIMARY KEY (ID),
    CONSTRAINT BOOK_AUTHOR_FK FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID) ON DELETE CASCADE,
    CONSTRAINT BOOK_GENRE_FK FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID) ON DELETE CASCADE);