version: '3'
services:
  mysql-service:
    image: mysql:8
    container_name: 'mysql_db'
    environment:
      - MYSQL_DATABASE=library
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - '3306'
    networks:
      - nw

  app-service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: 'library_java_app'
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-service:3306/library
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    networks:
      - nw
    restart: on-failure
    depends_on:
      - mysql-service
networks:
  nw:
    driver: bridge